services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data/:/var/lib/mysql:rw # persistent volume
      - ./mysqld.conf:/etc/mysql/mysql.conf.d/mysqld.cnf # config mysql server
    ports:
      - "3306:3306"
    environment:
      MARIADB_TCP_PORT: ${DB_PORT:-3306}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD:-LS4wt7e8}
      MARIADB_ROOT_HOST: '%'
      MARIADB_DATABASE: ${DB_NAME:-students}
      DB_USER: ${DB_USER:-student}
      DB_PASSWORD: ${DB_PASSWORD:-LS4wt7e8}
    networks:
      - app-network

  backend:
    build: ./backend
    restart: always
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-student}
      DB_PASSWORD: ${DB_PASSWORD:-LS4wt7e8}
      DB_NAME: ${DB_NAME:-students}
      DB_SCHEMA: ${DB_SCHEMA:-public}
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./front
    restart: always
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "3000:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    # Proxy API calls to backend
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge